excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://audhicaree.github.io
title: The Shubhankar Adhikari Monolgue
tagline: Because I struggle to write. Yet, that's all I do.
description: I was born to write, I know it. Instead, I spend in excess of ten hours each day at office, dabbling in senselessness. It is time things changed and I became myself.
paginate: 100